/**
 * Profiles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileSharingTokenData {
    id?: number;
    profileId?: number;
    token?: string | null;
    requiresAuthorization?: boolean;
    grantedAccessAt?: Date | null;
    isAccessGranted?: boolean;
    requestedAuthorizationAt?: Date | null;
    isRequestedAuthorization?: boolean;
}

